apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  timeout: 1h
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/helm
  prune: true
  validation: client
